# 
# Copyright (C) 2020 ArtXIA <https://github.com/artxia>
# <https://github.com/artxia/Action-NotionSite.git>
#

name: Deploy to Pages

on:
#  schedule:
#    - cron: "*/20 * * * *"
  workflow_dispatch:
    inputs:
    
jobs:
  build-and-deploy:
    runs-on: ubuntu-18.04
    
    steps:
      - uses: actions/checkout@v2

      - name: Checkout loconotion
        uses: actions/checkout@v2
        with:
          repository: leoncvlt/loconotion
          path: loconotion

      - name: Checkout this repo
        uses: actions/checkout@v2
        with:
          path: pages_repo

      - name: Build Loconotion docker image
        run: docker-compose build loconotion
        working-directory: loconotion

      - name: Run Loconotion
        run: |
          docker-compose run \
          -v "${GITHUB_WORKSPACE}/pages_repo/dist:/app/loconotion/dist" \
          -v "${GITHUB_WORKSPACE}/loconotion_settings.toml:/app/loconotion/site.toml" \
          loconotion "site.toml"
        working-directory: loconotion

      - name: Set env
        run: |
          echo "MY_FOLDER=pages_repo/dist/$(ls -1 pages_repo/dist | sed -n 1p)" >> $GITHUB_ENV

      - name: Test
        run: echo ${{ env.MY_FOLDER }}

      - name: Deploy to Pages
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: ${{ env.MY_FOLDER }}
          CLEAN: true
          SINGLE_COMMIT: true

      - name: Delete workflow runs
        uses: Mattraks/delete-workflow-runs@v2
        with:
          token: ${{ github.token }}
          repository: ${{ github.repository }}
          retain_days: 2
          keep_minimum_runs: 6
